bin/station.js, test/test.js
=> `station --version`. Closes #20

lib/saturn-node.js
the metric is TBD, however we can already solidify it in our data structures
=> metrics: add `totalEarnings`

README.md, bin/station.js, commands/index.js, commands/metrics.js, commands/station.js, lib/log.js, lib/paths.js, package-lock.json, package.json, test/test.js
=> `station metrics`. Closes #23

package-lock.json, package.json, test/test.js
`test` is creating issues in https://github.com/filecoin-station/core/pull/46, and it will take too much time for me to update the module myself. Therefore, I opened this PR to switch to `tap`, since it's similar enough, and well tested.
=> Switch to `tap` test runner

commands/activity.js, commands/logs.js, commands/metrics.js, commands/station.js, lib/paths.js, lib/util.js, package-lock.json, package.json, test/test.js
This securely prevents multiple stations from running at the same time, as suggested by @bajtos 🙏 
Also as you suggested @bajtos, I refactored the `maybeCreateFile` function.
=> add lockfile

lib/telemetry.js
For https://github.com/filecoin-station/core/pull/66#discussion_r1146124578
=> telemetry: add `arch`

package-lock.json, package.json, test/test.js
We need the extra stability that `mocha` has to offer
=> switch from `tap` to `mocha`

README.md, lib/paths.js
To match https://github.com/filecoin-station/zinnia/pull/166/files
=> fix default paths

README.md, commands/events.js, lib/activity.js, test/test.js
For https://github.com/filecoin-station/desktop/pull/621#discussion_r1162763138
=> Add `activity.id`

README.md, commands/activity.js, commands/events.js, lib/activity.js, test/test.js
For https://github.com/filecoin-station/desktop/pull/621#discussion_r1162760191
=> `activity.{date->timestamp}`

bin/station.js, commands/logs.js, lib/log.js
This adds libs for fetching logs, and makes the command use them
=> refactor log command

bin/station.js
Pulled out of https://github.com/filecoin-station/core/pull/104/files
=> station: refactor module list

lib/activity.js, lib/log.js, lib/metrics.js, lib/telemetry.js, tsconfig.json
Let's improve our TypeScript setup.
I am not enabling `strict` mode yet, as that produces over 50 compiler errors that I don't have the bandwidth to investigate & fix right now.
I propose merging this PR into #100 first and looking into enabling the `strict` mode later.
=> improve tsconfig + fix compiler errors

lib/bacalhau.js
https://github.com/bacalhau-project/bacalhau/releases/tag/v1.0.3
=> `bacalhau@v1.0.3`

lib/zinnia.js
- feat: upgrade zinnia to v0.14.0
- feat: upgrade spark to v1.3.0
=> feat: zinnia v0.14.0 and spark to v1.3.0

lib/zinnia.js
- link to https://github.com/filecoin-station/spark/issues/13
=> feat: upgrade spark to v1.4.0

lib/zinnia.js
See https://github.com/filecoin-station/spark/releases/tag/v1.5.0
=> feat: upgrade spark to v1.5.0

commands/station.js, test/cli.js
@bajtos hindsight please, I don't want to accidentally deploy a funded mainnet PR before landing this.
Closes #249
=> Screen wallet addresses. Closes #249

.github/workflows/dependabot-auto-approve-minor.yml
=> ci: add auto approve minor `@sentry/*` updates

.github/workflows/dependabot-auto-merge.yml
=> ci: add auto merge dependabot updates

lib/zinnia.js
https://github.com/filecoin-station/zinnia/releases/tag/v0.15.0
=> deps: upgrade Zinnia to v0.15.0

lib/zinnia.js
https://github.com/filecoin-station/spark/releases/tag/v1.6.0
=> deps: upgrade Spark to v1.6.0

commands/station.js, package-lock.json
Changes made to send scheduled rewards to desktop to satisfy https://github.com/filecoin-station/desktop/issues/1134
=> Send scheduled rewards to Station Desktop

lib/zinnia.js
Links:
- https://github.com/filecoin-station/roadmap/issues/52
=> feat: upgrade Spark to v1.7.0

lib/zinnia.js
Ref https://filecoinproject.slack.com/archives/C023K7D9GAX/p1703679868805479
=> Add auth to glif requests

lib/modules.js, lib/zinnia.js, package-lock.json, package.json
=> Download updates via ipfs, not github

lib/zinnia.js
Also report to Sentry when we weren't able to update source files after launch
=> zinnia: add report all update errors to sentry

lib/zinnia.js
~~CI is failing because Zinnia's release process hasn't finished yet: https://github.com/filecoin-station/zinnia/actions/runs/7802847939~~
=> feat: upgrade Zinnia to v0.17.0

lib/zinnia.js
This makes core refresh the contracts used while it's running.
Following the 3 commits should be the best way to review.
=> Add update contract addresses

lib/zinnia.js
Ref: https://github.com/filecoin-station/core/pull/356#discussion_r1496032902
=> zinnia: refactor main loop

lib/zinnia.js
Release notes:
https://github.com/filecoin-station/zinnia/releases/tag/v0.18.2
=> deps: upgrade Zinnia to v0.18.2

test/station-id.test.js
Links:
- https://github.com/filecoin-station/spark-api/pull/257
- https://github.com/filecoin-station/zinnia/pull/530
=> test: assert public key format & length

lib/zinnia.js
https://github.com/filecoin-station/zinnia/releases/tag/v0.18.3
=> deps: upgrade Zinnia to v0.18.3

lib/station-id.js, package.json, test/station-id.test.js
=> Fix station-id test noise. Closes #438

lib/zinnia.js
=> zinnia: update glif token

lib/zinnia.js
https://github.com/filecoin-station/zinnia/releases/tag/v0.19.1
=> feat: upgrade Zinnia to v0.19.1

commands/station.js, lib/contracts.js
See https://github.com/filecoin-station/desktop/issues/1547
=> fix: don't crash when getContractsWithRetry fails

lib/rewards.js
The functions accepts a list of Ethers Contract instances.
=> types: fix `contract` arg of `runUpdateRewardsLoop`

package.json
We need the post-install script.
I forgot to push this commit to #479 🙈
=> fix: include scripts in the npm package

bin/station.js
The old DSN has already been disabled
@bajtos FYI
=> Update Sentry DSN

lib/zinnia.js
Follow up for https://github.com/filecoin-station/core/pull/496, which missed a commit
=> fix remove voyager module

lib/zinnia.js
https://github.com/filecoin-station/zinnia/releases/tag/v0.20.0
=> feat: upgrade Zinnia to v0.20.0

lib/zinnia.js
https://github.com/filecoin-station/zinnia/releases/tag/v0.20.1
=> feat: upgrade Zinnia to v0.20.1

lib/modules.js, lib/zinnia.js
As advised by w3s in https://space-meridian.slack.com/archives/C027XP5BTGB/p1717581326121119?thread_ts=1717165521.276339&cid=C027XP5BTGB
Closes #552
=> Disable w3s cache on failed attempt. Closes #552

Dockerfile
=> chore: fix Dockerfile linter errors

.github/dependabot.yml
=> Update dependabot.yml to ensure Dependabot is set up to auto-update Docker dependencies

lib/zinnia.js
Closes CheckerNetwork/arweave-checker#9
=> Add `arweave` subnet. Closes CheckerNetwork/arweave-checker#9

README.md, lib/zinnia.js, test/checker.js
Adds experimental Walrus subnet. 
Closes https://github.com/CheckerNetwork/walrus-checker/issues/7
=> Add experimental walrus subnet.

.github/workflows/dependabot-auto-approve-always.yml
See https://github.com/CheckerNetwork/node/pull/725#discussion_r2054206744
=> ci: always auto-approve prettier config updates
