lib/log.js
lib/metrics.js

Since this is a CLI, we want stream `"error"` events to crash the process, rather than just logging to stderr

fix stream errors not crashing the process

---

lib/telemetry.js

For tracking how updates are rolled out
https://github.com/filecoin-station/desktop/pull/584

telemetry: add `version`

---

README.md
lib/paths.js
package.json
test/test.js

Based on https://github.com/filecoin-station/desktop/blob/e3db3b4d2c7bdef37cbf7a3cc31d8047933d5733/main/consts.js#L21-L47
https://github.com/filecoin-station/core/pull/66#discussion_r1145949770
Once Core has been integrated into Desktop, we can remove the logic from there.

add `$STATION_ROOT`

---

README.md
bin/station.js
commands/station.js
lib/paths.js
test/test.js

Closes #76.
Use `CACHE_ROOT` for Saturn for now.

Rework `ROOT_DIR` to `CACHE_ROOT` and `STATE_ROOT`. Closes #76

---

README.md
bin/station.js
commands/activity.js
test/test.js

This is for Station Desktop to load the initial Activity feed, without needing to store it itself

Add `--json` to `station activity`

---

README.md
commands/events.js
test/test.js

Add .date to activity events

---

README.md
bin/station.js
commands/metrics.js
commands/station.js
lib/metrics.js
lib/paths.js
test/test.js

For #92.
Similarly to logs, this persists module metrics both in a per-module file, and in a merged `all.log`. Thereby, multiple modules can persist their individual metrics, and there is still a merged view of them all.

Add merge module metrics. #92

---

.dockerignore
.github/workflows/ci.yml
.github/workflows/docker.yml
Dockerfile
bin/station.js
lib/saturn-node.js
test/metrics.js

- Fix Dockerfile to accommodate the latest changes and build a working Docker image again.
- Upgrade Saturn L2 Node to version [v0.5.1](https://github.com/filecoin-saturn/L2-node/releases/tag/v0.5.1)
- Add a new section to our CI workflow to build the Docker image, run it and check the activity log to verify that all modules have started.
- Partially revert 6bbd34c57fd7f07c5ce1324686ac9fd59f21c7a7 (#91). The "Docker" workflow is executed for release builds only; the pull requests are tested using the newly added section in the "CI" workflow.
More information on the users and permissions in the Node Docker images:
https://github.com/nodejs/docker-node/issues/740#issuecomment-458545074
Ideally, we would re-use the same workflow step to build the Docker image for release and for CI testing, …

ci: start Docker image and test output

---

lib/bacalhau.js

Update `bacalhau` to `v0.3.29`

---

lib/telemetry.js

Add per process core random id. Without this, we can't tell how many core instances are running - only how many distinct wallets are configured.
A core process will get a random id when it starts. Since you can run multiple cores on one machine, a machine id isn't feasible.

telemetry: add core id

---

Dockerfile
lib/telemetry.js

Without this we can't tell from a telemetry line whether a `wallet` hash identifies a destination wallet or the Station wallet.
Related: https://github.com/filecoin-station/desktop/pull/714

telemetry: add tag `deployment_type`

---

lib/bacalhau.js
lib/modules.js
lib/zinnia.js

Required for https://github.com/filecoin-station/desktop/pull/767

add `$ARCH` to install script

---

lib/modules.js

I don't know why, but the old flow made node crash with code 13, no error message

Fix unzip on Windows

---

lib/telemetry.js

Previously we weren't successfully filtering out errors like ones with `.code = 'ECONNRESET'`, because the `String(err)` only includes the message, no other properties:
```js
> const err = new Error('message')
> err.code = 'ECONNRESET'
> String(err)
> // => Error: message
```
`util.inspect()` fixes this:
```js
> util.inspect(err)
'Error: message\n' +
'    at REPL22:1:11\n' +
'    at Script.runInThisContext (node:vm:122:12)\n' +
'    at REPLServer.defaultEval (node:repl:567:29)\n' +
'    at bound (node:domain:433:15)\n' +
'    at REPLServer.runBound [as eval] (node:domain:444:12)\n' +
'    at REPLServer.onLine (node:repl:897:10)\n' +
'    at REPLServer.emit (node:events:523:35)\n' +
'    at REPLServer.emit (node:domain:489:12)\n' +
'    at [_onLine] [as _onLine] …
```

telemetry: also search err.code

---

lib/zinnia.js

Highlights:
- secure Lassie server using authorisation
- change IPFS retrieval timeouts to 1 day
Full release notes:
https://github.com/filecoin-station/zinnia/releases/tag/v0.13.0
Related: https://github.com/filecoin-station/spark/pull/8

feat: upgrade Zinnia to v0.13.0

---

commands/station.js
lib/bacalhau.js
lib/zinnia.js
package-lock.json
package.json

Alternative implementation to https://github.com/filecoin-station/core/pull/169.
Notable differences:
Instead of the zinnia lib restarting itself internally, we make `zinnia.start()` throw an error when it exists. Then, we use `p-retry()` to take care of restarting it

add restart modules

---

.github/workflows/ci.yml
README.md
commands/station.js
test/util.js

Closes #231
Temporary fix while Station Desktop doesn't yet support 0x/f4 addresses.

Add back f1 support (deprecated). Closes #231

---

commands/station.js
package-lock.json
package.json

@bajtos hindsight please
This fixes an error in Station Desktop, where you have it launch at boot, but your network isn't ready yet -> `core` fails to launch and `desktop` doesn't recover.
Alternatives considered:
- Remove address check from `core` when it's launched by `desktop`, which will only supply Station-created addresses. This would be the simplest solution. Need to double check with legal if we may add this option. Downside: If one of the Station wallets gets sanctioned, this doesn't catch it.
- Add retry logic to Station Desktop. I think this would be nicer overall, but a more difficult change. Wdyt?

Fix retry wallet address check

---

commands/station.js
lib/zinnia.js
package-lock.json
package.json

Can only pass 0x addresses to the contract

fix scheduled rewards for f4 address

---

Dockerfile

Interestingly enough, this seems to fix the network errors we observed before 🤷🏻‍♂️ 
Example of such errors:
```
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network request to https://registry.npmjs.org/is-network-error/-/is-network-error-1.0.0.tgz failed, reason: socket hang up
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
```

feat: upgrade Dockerfile to Node.js 20 LTS

---

lib/zinnia.js

https://github.com/filecoin-station/zinnia/releases/tag/v0.16.0
**Highlights ✨**
Upgrade Rusty Lassie to v0.8.0. We now configure Lassie's user agent to report the Go Lassie version plus our custom suffix, e.g. `lassie/v0.21.0-rs`.

feat: upgrade Zinnia to v0.16.0

---

lib/modules.js
lib/zinnia.js

Closes https://github.com/filecoin-station/roadmap/issues/53

Add automatic module updates. Closes filecoin-station/roadmap#53

---

lib/zinnia.js

Due to exponential backoff logic, 10 retries already take >1 minute to complete

zinnia: set max update retries to 10

---

commands/station.js
lib/modules.js
lib/paths.js
lib/zinnia.js

By storing the latest installed module version in a text file, prevent redundant updates.

Fix redundant module updates

---

.github/workflows/ci.yml
lib/zinnia.js
test/station.js

Zinnia started -> {Spark,Voyager} started

---

commands/station.js
lib/modules.js
lib/paths.js
lib/zinnia.js

The main directory isn't always writeable, eg when mounted inside an electron app. Therefore, store files inside CACHE_ROOT

fix store module sources in CACHE_ROOT

---

lib/zinnia.js

@bajtos do you know why TS didn't fail on this?
Discovered via Sentry: https://protocol-labs-ip.sentry.io/issues/4949926341/?project=4504792315199488&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=5

Fix `updateAllSourceFiles` signature

---

.github/workflows/ci.yml
lib/modules.js
package.json
tsconfig.json

- Drop node 16 support ([past EOL](https://github.com/nodejs/Release))
- Update tsconfig to support the `{ cause }` parameter on `Error()`
- Don't update the tsconfig module settings, as otherwise this happens:

update to node 18

---

lib/zinnia.js

Before:
```
[2024-02-08T09:38:58Z INFO  module:/Users/julian/Library/Caches/app.filstation.core/sources/spark/main] Getting current SPARK round details...
```
After:
```
[2024-02-08T09:42:37Z INFO  module:spark/main] Getting current SPARK round details...
```
This regression was introduced in https://github.com/filecoin-station/core/commit/f9ec3fd6a44089da62ee4c2a52a8e72350920621.

zinnia: fix module paths for logging

---

lib/zinnia.js

We don't want to show actual error stacks in Station Desktop

zinnia: fix verbose error activity

---

lib/zinnia.js

Saw this in Sentry:
```
Error: You are being rate limited
at S (file:///usr/src/app/node_modules/w3name/dist/index.mjs:1:2621)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Module.q (file:///usr/src/app/node_modules/w3name/dist/index.mjs:1:2298)
at async getLatestCID (file:///usr/src/app/lib/modules.js:106:20)
at async updateSourceFiles (file:///usr/src/app/lib/modules.js:142:15)
at async RetryOperation._fn (file:///usr/src/app/node_modules/p-retry/index.js:57:20) {
attemptNumber: 11,
retriesLeft: 0
}
```
https://protocol-labs-ip.sentry.io/issues/4952775000/?project=4504792315199488&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=2
And w3name says:
> There is a rate limit of 30 requests per 10 seconds per IP.
Since this …

fix don't ddos w3name

---

lib/modules.js

Fix occasional `ENOENT` during `tar.extract()`. Closes #1399

---

lib/zinnia.js

I noticed looking at the `core-fly` logs that multiple update loops were running in parallel. This fixes the case when the abort controller is triggered but the async function that's currently running doesn't listen for it

zinnia: fix end update loops outside of signal event

---

lib/zinnia.js

- Add the module name & the exit code to the message
- Remove Zinnia & module main file path from the message
The goal is to allow Sentry to group all errors with the same cause in a single issue.
Add the last 50 lines from the Execa error message (including stdout & stderr) into the `extra` fields sent to Sentry.
This is a follow-up for https://github.com/filecoin-station/core/pull/377

rework Zinnia errors reported to Sentry

---

lib/zinnia.js

Before this change, Sentry was creating multiple issue for the same error depending on the inner details (e.g. the module stderr).
After this change, Sentry should look only at the module name and the exit reason (exit code or signal) to determine the group.

Add custom Sentry grouping for Zinnia exit errors

---

lib/zinnia.js

There are some issues with the zinnia loop end logic. See for example these logs from `core-fly`:
```
Mar 26 15:03:07 core-fly [spark]  ⇣ checking for updates
Mar 26 15:03:08 core-fly [voyager]  ⇣ checking for updates
Mar 26 15:03:08 core-fly [spark]  ⇣ checking for updates
Mar 26 15:03:08 core-fly [voyager]  ⇣ checking for updates
Mar 26 15:03:08 core-fly [voyager]  ✓ no update available
Mar 26 15:03:08 core-fly [spark]  ✓ no update available
Mar 26 15:03:08 core-fly [spark]  ✓ no update available
Mar 26 15:03:08 core-fly [voyager]  ✓ no update available
```
We can see that 2 update loops were running at once, which means that in a previous `run()` invocation the loop should have been aborted, but wasn't.
This PR fixes this by only using one method: `controller.abort()` for aborting, and …

Fix main loop not ending properly

---

lib/zinnia.js

When recording an issue for a module exit event, include the module name in custom tags. I hope this will make issues easier to search and make it easier to merge similar issues.

feat: add moduleName to Sentry issue reports

---

lib/zinnia.js

The previous patch wasn't sufficient, core-fly got stuck after this:
When we threw an error, no clean up happened. This is now fixed. And also, we now let execa kill all child processes through the AbortSignal, which helps tighten up the clean up further.

Fix more zinnia loop issues

---

lib/zinnia.js

There's nothing that operators can do about these crashes. This PR changes the activity type into "Info"

change Voyager crashes into `info`

---

.github/workflows/ci.yml
lib/modules.js

- **chore: fix TypeScript errors related to `pipeline`**
- **ci: add TypeScript check to the CI workflow**
This is a follow-up for https://github.com/filecoin-station/core/pull/410

chore: fix TypeScript errors related to `pipeline`

---

.github/workflows/ci.yml

The release line 19.x is not supported by the Node.js project anymore.
See https://nodejs.org/en/about/previous-releases

ci: drop Node.js 19.x

---

lib/zinnia.js

https://github.com/filecoin-station/zinnia/releases/tag/v0.18.1
Blocked by:
- #406
Links:
- filecoin-station/roadmap#96

deps: upgrade Zinnia to v0.18.1

---

lib/station-id.js

When creating a new station identity and no PASSPHRASE was provided by the operator, print a warning instructing them to provide one.
Example output:
```
❯ npm start
> @filecoin-station/core@20.2.0 start
> cross-env FIL_WALLET_ADDRESS=0x000000000000000000000000000000000000dEaD STATE_ROOT=.state CACHE_ROOT=.cache node ./bin/station.js
*****************************************************************************************
The private key of the identity of your Station instance will be stored in plaintext.
We strongly recommend you to configure PASSPHRASE environment variable to enable
Station to encrypt the private key stored on the filesystem.
*****************************************************************************************
(node:96209) ExperimentalWarning: The Ed25519 Web …
```

feat: warn user about missing PASSPHRASE

---

lib/station-id.js

stdout is reserved for JSON-formatted activity-log events
The Sentry Issue where I learned about the problem: https://space-meridian.sentry.io/issues/5259340154/?project=6762462&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=7d&stream_index=1&utc=true

fix: print station-id logs to stderr

---

Dockerfile

Slim shaves about 400MB off the container when installed. It is always better to have smaller images, especially when installing these at the edge on routers and such.

Change Docker base image to slim

---

commands/station.js

This way we only get 0x addresses submitted to `{spark,voyager}-api`

fix pass eth address to zinnia

---

bin/station.js
lib/zinnia.js

zinnia: fix double reporting of crash errors

---

commands/station.js
lib/telemetry.js

Closes #404
I didn't see a good way to test free disk space (depends on mount points etc), but that's not relevant for Station modules atm anyway.

Add machine info to telemetry. Closes #404

---

bin/station.js
lib/zinnia.js

The problem was `if (!signal.aborted)`: We only performed the special Sentry error transformation when a child process exited on its own. When the AbortController was triggered (say because there was a module update), then `signal.aborted` was always `true`, and therefore the special Sentry code didn't run.
This condition was a mistake, and is now removed in this PR. We want to run the code block on every child process exit.

Fix zinnia sentry grouping

---

commands/station.js
test/cli.js

When the user provides `FIL_WALLET_ADDRESS` that's rejected by our screening service, return a different exit code to allow Station Desktop to detect this error and apply different error handling.
See https://space-meridian.sentry.io/issues/4996347608/events/7c27f714175449b7b347bbae476151b6/

feat: exit code 2 when walled failed screening

---

commands/station.js
lib/contracts.js
lib/obj.js
lib/rewards.js
lib/zinnia.js

Slack discussions with context:
- https://space-meridian.slack.com/archives/C06RPCL6QGL/p1715686302232529
- https://filecoinproject.slack.com/archives/C023K7D9GAX/p1715419803449009

move rewards update loop out of zinnia loop

---

lib/modules.js

@bajtos I have finally been able to reproduce the lstat errors that are reported so often. And for me, the only way to recover was this quick fix. I didn't have time to look into it more properly.
Since the diff is indentation heavy, the gist is this: Remove the try/catch that removes `outDir` when the download failed. I don't know why this fixes it, or whether this introduces regressions.
Closes #465

modules: fix lstat error on `outDir`. Closes #465

---

.npmignore
package.json

See the discussion in https://github.com/filecoin-station/desktop/pull/1546
We shouldn't be shipping local state & cache files created on the developer
machine. We also don't need to ship tests, GitHub configuration and more.
List of files packaged by the new package config:
```
npm notice
npm notice 📦  @filecoin-station/core@20.6.2
npm notice === Tarball Contents ===
npm notice 12.6kB LICENSE.md
npm notice 6.1kB  README.md
npm notice 1.1kB  bin/station.js
npm notice 4.9kB  commands/station.js
npm notice 68B    dist/bin/station.d.ts
npm notice 111B   dist/bin/station.d.ts.map
npm notice 155B   dist/commands/activity.d.ts
npm notice 132B   dist/commands/activity.d.ts.map
npm notice 224B   dist/commands/index.d.ts
npm notice 112B   dist/commands/index.d.ts.map
npm notice 151B …
```

feat: allow-list files included in the npm package

---

lib/contracts.js

Now that the contract update loop is decoupled from modules crashing, we can fetch updates immediately without needing to worry about ddosing w3name

contracts: update wait after fetch

---

README.md

Update the instructions to use Node.js 20.x (was 18.x). 
I did not test the new instructions on a Debian machine, but I did verify that the new URL exists and returns a script that looks legitimate.

docs: update Node.js version on Debian

---

commands/station.js
lib/contracts.js
lib/zinnia.js
package-lock.json
package.json

```
> tsc -p .
Error: commands/station.js(139,[7](https://github.com/filecoin-station/core/actions/runs/9265546175/job/25487806561?pr=487#step:6:8)): error TS2353: Object literal may only specify known properties, and 'abi' does not exist in type '{ provider: any; contracts: any; onActivity: any; }'.
Error: commands/station.js(139,7): error TS1[8](https://github.com/filecoin-station/core/actions/runs/9265546175/job/25487806561?pr=487#step:6:9)004: No value exists in scope for the shorthand property 'abi'. Either declare one or provide an initializer.
Error: Process completed with exit code 2.
```
@bajtos would you do the honors? 🙏

refactor using `@filecoin-station/spark-impact-evaluator`

---

bin/station.js

The most frequently submitted error atm is `Command was canceled: /usr/src/app/modules/zinnia/zinniad voyager/main.js`, which won't happen on current Core releases

Rotate Sentry token

---

lib/zinnia.js

Bump [zinnia](https://github.com/filecoin-station/zinnia) from 0.20.1 to 0.20.2.
- [Release notes](https://github.com/filecoin-station/zinnia/releases/v0.20.2)
- [Commits](https://github.com/filecoin-station/zinnia/compare/v0.20.1...v0.20.2)

deps: bump Zinnia from 0.20.1 to 0.20.2

---

lib/zinnia.js

Remove the `exit` event handler which would create duplicate activity events on a crash.

fix redundant exit message

---

README.md
bin/station.js
commands/station.js
lib/station-id.js
test/cli.js
test/station-id.test.js

For https://github.com/filecoin-station/desktop/issues/1726
I decided to add this flag instead of a new exit code (as suggested in https://github.com/filecoin-station/desktop/issues/1726#issuecomment-2262594686), because with the new exit code Station Desktop needs to know where Station Core stores its internal files, and this coupling isn't necessary.

Add `--recreateStationIdOnError`

---

bin/station.js

Stop receiving auto-updater errors from old versions, e.g.
https://space-meridian.sentry.io/issues/5563125691/

chore: rotate Sentry DSN

---

lib/zinnia.js

Bump [zinnia](https://github.com/filecoin-station/zinnia) to 0.20.3.
- [Release notes](https://github.com/filecoin-station/zinnia/releases/v0.20.3)
- [Commits](https://github.com/filecoin-station/zinnia/compare/v0.20.2...v0.20.3)
Bring in the following fix
- https://github.com/filecoin-station/zinnia/pull/593
See also
- https://github.com/filecoin-station/core/issues/583

deps: bump Zinnia from 0.20.3 to 0.20.3

---

lib/zinnia.js

When Zinniad is killed via SIGTERM/SIGKILL/SIGINT, don't report the error to Sentry.
These signal codes are triggered when somebody terminates the process from outside. It's not a problem in Zinnia, there is nothing we can do about this.
Before:
```
ERROR Spark crashed via signal SIGTERM
Reporting the problem to Sentry for inspection by the Station team.
Zinnia main loop ended
Starting zinniad with config CliArgs { /* ... */ }
```
After:
```
ERROR Spark crashed via signal SIGTERM
Zinnia main loop ended
Starting zinniad with config CliArgs { /* ... */ }
```
The Sentry issue:
- https://space-meridian.sentry.io/issues/5098171677/

fix: don't report SIGTERM & friends to Sentry

---

lib/rewards.js

https://github.com/space-meridian/roadmap/issues/161

Read scheduled rewards from `spark-rewards`

---

lib/modules.js

https://github.com/filecoin-station/zinnia/issues/485#issuecomment-2406646096

module: add report tar debug information

---

lib/modules.js

Trying to fix reported cases of `sources/spark/main.js` missing, while `sources/spark` is there.
This is the same path we're checking below - only if the main file `main.js` exists, consider the module as functional. This is still not great but should fix some cases. In the future, use hashes to check validity of _all_ files on disk.

modules: ensure main file also exists

---

lib/contracts.js
lib/modules.js
lib/telemetry.js

Ref https://filecoinproject.slack.com/archives/C06SFMDMUAU/p1734275910797789
Related: https://github.com/filecoin-station/core/issues/651

fix don't report unactionable w3name request errors to Sentry

---

Dockerfile

Partially Fixes https://github.com/CheckerNetwork/roadmap/issues/210
Updated the Node.js base image from node:20-slim to node:22-slim as requested in issue 210 of the roadmap repository.

updated the base node image in Dockerfile

---

.github/workflows/ci.yml

Stop running linters for every Node.js version we support. It's enough to run linters on a single Node.js version.
This should fix the CI failure in #710 caused by a linter crash on Node.js v18.

ci: extract linting to a parallel job

---

.github/workflows/dependabot-auto-approve-minor.yml

This is a follow-up for #710 where we switched from standard to neostandard.

ci: auto-approve neostandard updates

---

README.md
lib/zinnia.js
test/checker.js

Removes arweave and walrus checkers and all related code and docs.

chore: Remove arweave and walrus checker modules
